spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
