FROM openjdk:11-jdk-slim

#ENV JAVA_OPTS " -Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom"

#WORKDIR /

#VOLUME /tmp

ARG JAR_FILE=../../../target/eureka-service-1.0-SNAPSHOT.jar

ADD ${JAR_FILE} eureka-service.jar
#RUN sh -c 'touch /eureka-service.jar'

#EXPOSE 8761

ENTRYPOINT ["java", "-jar", "eureka-service.jar"]
